# Generated by Django 4.2.3 on 2023-07-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('aditorial', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=30)),
                ('fechaEntrada', models.DateTimeField(null=True)),
                ('tipoAdquisicion', models.CharField(max_length=40)),
                ('edicion', models.CharField(max_length=40)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Readers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('año', models.CharField(max_length=10)),
                ('seccion', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('numeroTelefono', models.IntegerField(max_length=10)),
                ('direccion', models.TextField(max_length=150)),
            ],
        ),
    ]
