# Generated by Django 4.2.3 on 2023-07-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_aditorial_books_editorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='fechaEntrada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
