# Generated by Django 4.2.3 on 2023-07-16 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_readers_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='idLector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.readers'),
        ),
    ]
