# Generated by Django 4.2.3 on 2023-07-17 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_loans_idlector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='idLibro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.books'),
        ),
    ]
