# Generated by Django 4.2.3 on 2023-08-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_readers_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='readers',
            name='prestamos',
            field=models.ManyToManyField(to='app.loans'),
        ),
        migrations.AlterField(
            model_name='books',
            name='fechaEntrada',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='readers',
            name='direccion',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
