# Generated by Django 4.2.3 on 2023-08-09 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_readers_prestamos_alter_books_fechaentrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readers',
            name='prestamos',
        ),
    ]
