# Generated by Django 4.2.5 on 2023-09-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_readers_prestamos'),
    ]

    operations = [
        migrations.AddField(
            model_name='readers',
            name='es_profesor',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='readers',
            name='año',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='readers',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='readers',
            name='especialidad',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='readers',
            name='seccion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
