# Generated by Django 4.2.5 on 2023-09-24 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_readers_es_profesor_alter_readers_año_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readers',
            old_name='es_profesor',
            new_name='esDocente',
        ),
    ]
