# Generated by Django 4.2.5 on 2023-09-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_loans_fechaprestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='fechaEntrega',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='fechaPrestamo',
            field=models.DateField(),
        ),
    ]
