# Generated by Django 5.0.1 on 2024-02-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_loans_fechaprestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='fechaEntrada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
